# -*- coding: utf-8 -*-
"""DS 1115 - 19 March 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zowgxf1bralvZrnQHDx27QFdT6qILIIg
"""

class Animal:
    def __init__(self, name):
        self.name = name
    def make_sound(self):
        print("Generic Sound")

class Dog(Animal):
    def __init__(self, name, color):
        super().__init__(name)
        self.color = color
    def sleep(self):
        print("Dog is sleeping")
    def make_sound(self):
        print("Bark")
        super().make_sound()


dog = Dog("Buddy", "Black")

dog.make_sound()
print(dog.name)

class Father:
    def __init__(self, name):
        self.father_name = name
    def print_name(self):
        print(self.father_name)

class Mother:
    def __init__(self, name):
        self.mother_name = name
    def print_name(self):
        print(self.mother_name)

class Child(Mother, Father):
    def __init__(self, name, father_name, mother_name):
        Father.__init__(self, father_name)
        Mother.__init__(self, mother_name)
        self.child_name = name
    def print_name(self):
        print(self.child_name)
        super().print_name()

child = Child("Hasan", "Ahmed", "Akter")
child.print_name()

class F:
    def __init__(self):
        print("Talking from F")
class E:
    def __init(self):
        print("Talking from E")

class A(F):
    def __init__(self):
        print("Talking from A")
        super().__init__()
class B(E):
    def __init__(self):
        print("Talking from B")
        super().__init__()

class C(A, B):
    def __init__(self):
        super().__init__()
c = C()

