# -*- coding: utf-8 -*-
"""DS 1115 12 March 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kF-0Ai-2g4cIRWZOhbnZCb_tTvOVxJX
"""

class Point3D:
    def __init__(self, x, y, z):
        self.x=x
        self.y=y
        self.z=z
    def copy(self):
        return Point3D(self.x, self.y, self.z)
    def __str__(self):
        return f"({self.x},{self.y}, {self.z})"
    def scale(self, n):
        self.x *= self.x
        self.y *= self.y
        self.z *= self.z

p1 = Point3D(1, 2, 3)
p2 = p1
p3 = p2.copy()

p1.scale(2)
p2.scale(2)
p3.scale(2)

print(p1, p2, p3)

class Animal:
    def make_sound(self):
        print("Some Generic Sound")

class Dog(Animal):
    # method overriding
    def make_sound(self):
        print("Bark")

dog = Dog()
dog.make_sound()

# MRO = Method Resolution Order
print(Dog.mro())

